[profile.default]
optimizer = true
optimizer_runs = 200
solc-version = "0.8.16"
verbosity = 1
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
test = 'test'
cache_path  = 'cache-foundry'

# See more config options https://github.com/gakonst/foundry/tree/master/config
