name: coverage

on: [pull_request]

jobs:
  coverage-foundry:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18]
    steps:
      - name: Check out
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: yarn
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
      - run: yarn coverage --report lcov
      - name: Setup LCOV
        uses: hrishikesh-kadam/setup-lcov@v1
      - name: Report code coverage
        uses: zgosalvez/github-actions-report-lcov@v3
        with:
          coverage-files: lcov.info
          artifact-name: code-coverage-report
          github-token: ${{ secrets.PR_COMMENT_TOKEN }}
          update-comment: true
      - name: Report line coverage detail
        uses: romeovs/lcov-reporter-action@v0.2.16
        with:
          github-token: ${{ secrets.PR_COMMENT_TOKEN }}
          lcov-file: ./lcov.info
