name: coverage

on: [push, pull_request]

jobs:
  coverage-foundry:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16]
    steps:
      - name: Check out
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        run: yarn
      - name: Install Foundry
        uses: onbjerg/foundry-toolchain@v1
        with:
          version: nightly
        run: yarn coverage-forge
