on: [ workflow_dispatch ]

name: invariant-test

jobs:
  invariant-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18 ]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
      - id: forge_test
        run: forge test -vvv --mc BaseInvariantTest --fork-url https://optimism.llamarpc.com/sk_llama_115e7405eff4c29287d6ff9a0275bf84
        continue-on-error: true

