on: [push, pull_request]

name: test

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn
      - uses: onbjerg/foundry-toolchain@v1
        with:
          version: nightly
        run: forge test --fork-url https://arbitrum.llamarpc.com
