on: [push, pull_request]

name: test

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn
      - uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      - id: forge_test
        run: forge test --fork-url https://arbitrum.llamarpc.com/sk_llama_3f92d666a172604faf69e469a67ec6ea
        continue-on-error: true
      - name: Retry if fail forge test
        if: steps.forge_test.outcome == 'failure'
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 10   # Total time before giving up
          max_attempts: 3      # Total number of attempts
          command: forge test --fork-url https://arbitrum.llamarpc.com/sk_llama_3f92d666a172604faf69e469a67ec6ea
          retry_wait_seconds: 60    # Delay between retries
